import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../comp/header'
import Footer from '../comp/footer'
import Main from '../comp/main'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pricing Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bootstrap_icon.png" />
      </Head>

      <Header/>

      <Main/>

      <Footer/>
    </div>
  )
}
